### ISSUE TITLE
RedisConsumer get messages after downtime

### ISSUE THREAD

**Issue by me2nardo** [davidmarquis/redisq#1]
> Reliable delivery: Each consumer on a queue will receive each message even if they are temporarily offline.

and after start consumer how we can get them ? (maybe i have something missing)

We get only new messages. 
#
thx
 ```
@Bean
    public RedisMessageQueue myQueue(){
        RedisMessageQueue redisMessageQueue = new RedisMessageQueue();
        redisMessageQueue.setQueueName("Sending");
        redisMessageQueue.setRedisOps(redisOps());


        redisMessageQueue.setDefaultConsumerId("defaultGetter");

        return redisMessageQueue;
    }

    @Bean
    public RedisOps redisOps(){
        RedisOps redisOps = new RedisOps();
        redisOps.setRedisTemplate(redisTemplateQ());

        return redisOps;
    }


    @Bean
    public MessageProducer messageProducer(){
       MessageProducerImpl messageProducer = new MessageProducerImpl();
       messageProducer.setQueue(myQueue());
       messageProducer.setRedisOps(redisOps());
       messageProducer.setDefaultTimeToLive(10);
       messageProducer.setDefaultTimeToLiveUnit(TimeUnit.MINUTES);
       return messageProducer;
    }

    @Bean
    public MessageConsumer messageConsumer(){
        MessageConsumer messageConsumer = new MessageConsumer();
        messageConsumer.setQueue(myQueue());
        messageConsumer.setConsumerId("someConsumerId");
        messageConsumer.setMessageListener(new SomeListener());
        messageConsumer.setAutoStartConsumers(true);
        messageConsumer.setRedisOps(redisOps());
        messageConsumer.setRetryStrategy(new MaxRetriesStrategy(5));

        messageConsumer.setThreadingStrategy(new MultiThreadingStrategy(4));
        return messageConsumer;
    }

```

**Comment by davidmarquis** [comment]
The way you've set things up, you have a producer and a consumer that both exist simultaneously in your application... this would basically mean that every message produced by the producer is immediately (in the next second) consumed by the consumer. 
Can you give more details on how you tested and made your observation that past messages were not delivered?

**Comment by me2nardo** [comment]
1. start producer and consumer (in my case it's different applications)
all messages are received
2. then i stop consumer 
my last id was 90

> 127.0.0.1:6379> keys *
> 1) "\xac\xed\x00\x05t\x00\x1aredisq.Sending.messages.89"
> 2) "\xac\xed\x00\x05t\x00\x18redisq.Sending.consumers"
> 3) "\xac\xed\x00\x05t\x00\x1aredisq.Sending.messages.90"
> 4) "\xac\xed\x00\x05t\x00\x15redisq.Sending.nextID"
> 5) "\xac\xed\x00\x05t\x00\x1aredisq.Sending.messages.88"
> 6) "\xac\xed\x00\x05t\x00\x1aredisq.Sending.messages.87"
> 127.0.0.1:6379> 
> 

And send new message
4) "\xac\xed\x00\x05t\x00\x1aredisq.Sending.messages.91"
it's has been successfully stored in redis.

3. But when i start "consumer" i get only new messages. (after 91)
And those messages(91) when the consumer has been down , they are ignored.

How we can read them ?
Manually upload messages before "consumers start" and check them

**Comment by davidmarquis** [comment]
If your consumer (identified by its "consumer ID") has already processed specific messages (87-90 in your example), those messages will not be re-delivered... 

Are you expecting past messages to be re-delivered to your consumer? 
If you have multiple consumers on your queue (fan-out queue), then make sure each logical consumer is assigned a different Consumer ID (see `MessageConsumer.consumerId`)

**Comment by me2nardo** [comment]
> If your consumer (identified by its "consumer ID") has already processed specific messages (87-90 in your example), those messages will not be re-delivered...

at 90 I stop consumer and then send new message ID 91. Then start consumer and send again new message 92 . 

..
1. Message with ID 92 will delivered 
2. But message 91 not delivered because consumer was down

> Are you expecting past messages to be re-delivered to your consumer?

i expect only messages that was not delivered (in my case  91) when all consumers was down.

I can show example with test cases

**Comment by davidmarquis** [comment]
Yep the example might help. Let's see what that brings to the table.

The expected behaviour when submitting a message is described [here](https://github.com/davidmarquis/redisq/blob/master/src/test/resources/cucumber/features/producer.feature):

``` cucumber
Scenario: On a queue with 2 registered consumers, a Producer publishes a message to all Consumers
    Given A queue named "some.topic" exists
    And   A producer exists on queue named "some.topic"
    And   A consumer with ID "consumer1" is registered on queue named "some.topic"
    And   A consumer with ID "consumer2" is registered on queue named "some.topic"

    When The producer creates a message with content "toto"
    And  submits the message to all consumers

    Then A Redis list should exist in key "redisq.some.topic.queues.consumer1" with 1 element
    And  A Redis list should exist in key "redisq.some.topic.queues.consumer2" with 1 element
```

**Comment by me2nardo** [comment]
Scenario: On a queue with no registered consumers(downtime), a Producers submits a message with a specified TTL
Given A queue named "Sending" exists
    And   A producer exists on queue named "Sending"
    And   No consumer is watching the queue

    When The producer creates a message with content "campaign"
    2016-12-21 14:41:36.133  INFO 15668 --- [nio-8081-exec-1] o.g.m.p.controller.SenderRestController  : Perform submit:Campaign{id=1, longittude=2.0, lattitude=1.0, radius=0, startTime=null, endTime=null}
    And  specifies a time to live of 10 Min
    And  submits the message to all consumers

    And Get In redis   


1) "\xac\xed\x00\x05t\x00\x15redisq.Sending.nextID"
2) "\xac\xed\x00\x05t\x00\x19redisq.Sending.messages.1"


    Then Start Consumer
    After Producer Send new messages  "campaign"  
    2016-12-21 14:43:17.435  INFO 15668 --- [nio-8081-exec-3] o.g.m.p.controller.SenderRestController  : Perform submit:Campaign{id=1, longittude=2.0, lattitude=1.0, radius=0, startTime=null, endTime=null}
    2016-12-21 14:43:30.153  INFO 15668 --- [nio-8081-exec-5] o.g.m.p.controller.SenderRestController  : Perform submit:Campaign{id=2, longittude=2.0, lattitude=1.0, radius=0, startTime=null, endTime=null}
    2016-12-21 14:43:56.781  INFO 15668 --- [nio-8081-exec-7] o.g.m.p.controller.SenderRestController  : Perform submit:Campaign{id=3, longittude=2.0, lattitude=1.0, radius=0, startTime=null, endTime=null}
    Then Consumer get messages 
    2016-12-21 14:43:17.453  INFO 2544 --- [sumer[Sending]0] o.g.m.consumer.service.CampaignListener  : Start receive campaign:2
    2016-12-21 14:43:17.453  INFO 2544 --- [sumer[Sending]0] o.g.m.consumer.service.CampaignListener  : Campaign:Campaign{id=1, longittude=2.0, lattitude=1.0, radius=0, startTime=null, endTime=null}
    2016-12-21 14:43:30.170  INFO 2544 --- [sumer[Sending]2] o.g.m.consumer.service.CampaignListener  : Start receive campaign:3
    2016-12-21 14:43:30.170  INFO 2544 --- [sumer[Sending]2] o.g.m.consumer.service.CampaignListener  : Campaign:Campaign{id=2, longittude=2.0, lattitude=1.0, radius=0, startTime=null, endTime=null}
    2016-12-21 14:43:56.792  INFO 2544 --- [sumer[Sending]2] o.g.m.consumer.service.CampaignListener  : Start receive campaign:4
    2016-12-21 14:43:56.792  INFO 2544 --- [sumer[Sending]2] o.g.m.consumer.service.CampaignListener  : Campaign:Campaign{id=3, longittude=2.0, lattitude=1.0, radius=0, startTime=null, endTime=null}

127.0.0.1:6379> keys *
1) "\xac\xed\x00\x05t\x00\x15redisq.Sending.nextID"
2) "\xac\xed\x00\x05t\x00\x19redisq.Sending.messages.2"
3) "\xac\xed\x00\x05t\x00\x19redisq.Sending.messages.4"
4) "\xac\xed\x00\x05t\x00\x18redisq.Sending.consumers"
5) "\xac\xed\x00\x05t\x00\x19redisq.Sending.messages.3"
6) "\xac\xed\x00\x05t\x00\x19redisq.Sending.messages.1"
127.0.0.1:6379>


Message with ID 1 does not receive it's store only on redis.
Link to example https://github.com/me2nardo/redisq-example

**Comment by me2nardo** [comment]
I fix it with 
redisMessageQueue.setQueueDequeueStrategy(new RandomQueueDequeueStrategy(redisOps()));

and all messages after down time received.

**Comment by davidmarquis** [comment]
When a producers [submits a message to a queue](https://github.com/davidmarquis/redisq/blob/master/src/main/java/ca/radiant3/redisq/producer/MultiConsumerSubmissionStrategy.java#L21), it checks for all registered consumers and adds an ID in a Redis LIST corresponding to each registered consumer.

At that point if there is no live consumer, a Redis LIST with key `redisq.[QUEUE].queue.[CONSUMERID]` [should exist](https://github.com/davidmarquis/redisq/blob/master/src/main/java/ca/radiant3/redisq/utils/KeysFactory.java#L7).

In your example, there's no such LIST, you are listing only two keys:
 1. `\xac\xed\x00\x05t\x00\x15redisq.Sending.nextID`
 1. `\xac\xed\x00\x05t\x00\x19redisq.Sending.messages.1`

This would probably mean a consumer has consumed the submitted message.
