### ISSUE TITLE
is good project but Configuration file writing is tedious

### ISSUE THREAD

**Issue by xiaofanku** [davidmarquis/redisq#8]
my code :
`
    //base redis mq
    @Bean
    public PayloadSerializer payloadSerializer(){
        return new com.github.davidmarquis.redisq.serialization.GsonPayloadSerializer();
    }
    @Bean("redisOps")
    public RedisOps buildRedisMQOps(){
        RedisOps ro = new com.github.davidmarquis.redisq.persistence.RedisOps();
        //ro.setRedisTemplate(redisTemplate);
        return ro;
    }
    @Bean("redisMemberQueue")
    public RedisMessageQueue redisMsQueue(){
        RedisMessageQueue mq =  new com.github.davidmarquis.redisq.RedisMessageQueue();
        mq.setQueueName("queue.member");
        //mq.setRedisOps(redisOps);
        return mq;
    }
    // loop event
    @Bean("memberSignUpProducer")
    public MessageProducer<MemberSignUpEvent> signUpProducer(@Qualifier("redisMemberQueue") RedisMessageQueue redisMemberQueue){
        DefaultMessageProducer<MemberSignUpEvent> dmq = new com.github.davidmarquis.redisq.producer.DefaultMessageProducer<>();
        dmq.setQueue(redisMemberQueue);
        return dmq;
    }
    @Bean("memberSignInProducer")
    public MessageProducer<MemberSignInEvent> signInProducer(@Qualifier("redisMemberQueue") RedisMessageQueue redisMemberQueue){
        DefaultMessageProducer<MemberSignInEvent> dmq = new com.github.davidmarquis.redisq.producer.DefaultMessageProducer<>();
        dmq.setQueue(redisMemberQueue);
        return dmq;
    }
    @Bean("memberSignOutProducer")
    public MessageProducer<MemberSignOutEvent> signOutProducer(@Qualifier("redisMemberQueue") RedisMessageQueue redisMemberQueue){
        DefaultMessageProducer<MemberSignOutEvent> dmq = new com.github.davidmarquis.redisq.producer.DefaultMessageProducer<>();
        dmq.setQueue(redisMemberQueue);
        return dmq;
    }
    // loop listener
    @Bean
    public MessageConsumer<MemberSignUpEvent> promoteRoleConsumer(@Qualifier("redisMemberQueue") RedisMessageQueue redisMemberQueue, @Qualifier("promoteRole") MessageListener<MemberSignUpEvent> promoteRole){
        MessageConsumer<MemberSignUpEvent> messageConsumer = new com.github.davidmarquis.redisq.consumer.MessageConsumer<>();
        messageConsumer.setQueue(redisMemberQueue);
        messageConsumer.setConsumerId("SignUpEvent.PromoteRole");
        messageConsumer.setMessageListener(promoteRole);
        return messageConsumer;
    }
    @Bean("promoteRole")
    public MessageListener<MemberSignUpEvent> promoteRoleListener(){
        return new MemberSignUpPromoteRoleListener();
    }

    @Bean
    public MessageConsumer<MemberSignUpEvent> inviteCodeConsumer(@Qualifier("redisMemberQueue") RedisMessageQueue redisMemberQueue, @Qualifier("inviteCode") MessageListener<MemberSignUpEvent> inviteCode){
        MessageConsumer<MemberSignUpEvent> messageConsumer = new com.github.davidmarquis.redisq.consumer.MessageConsumer<>();
        messageConsumer.setQueue(redisMemberQueue);
        messageConsumer.setConsumerId("SignUpEvent.InviteCode");
        messageConsumer.setMessageListener(inviteCode);
        return messageConsumer;
    }
    @Bean("inviteCode")
    public MessageListener<MemberSignUpEvent> inviteCodeListener(){
        return new MemberSignUpInviteCodeListener();
    }

    @Bean
    public MessageConsumer<MemberSignUpEvent> registerNoticeConsumer(@Qualifier("redisMemberQueue") RedisMessageQueue redisMemberQueue, @Qualifier("registerNotice") MessageListener<MemberSignUpEvent> registerNotice){
        MessageConsumer<MemberSignUpEvent> messageConsumer = new com.github.davidmarquis.redisq.consumer.MessageConsumer<>();
        messageConsumer.setQueue(redisMemberQueue);
        messageConsumer.setConsumerId("SignUpEvent.Notice");
        messageConsumer.setMessageListener(registerNotice);
        return messageConsumer;
    }
    @Bean("registerNotice")
    public MessageListener<MemberSignUpEvent> registerNoticeListener(){
        return new MemberSignUpNoticeListener();
    }

    @Bean
    public MessageConsumer<MemberSignInEvent> loginNoticeConsumer(@Qualifier("redisMemberQueue") RedisMessageQueue redisMemberQueue, @Qualifier("loginNotice") MessageListener<MemberSignInEvent> loginNotice){
        MessageConsumer<MemberSignInEvent> messageConsumer = new com.github.davidmarquis.redisq.consumer.MessageConsumer<>();
        messageConsumer.setQueue(redisMemberQueue);
        messageConsumer.setConsumerId("SignInEvent.Notice");
        messageConsumer.setMessageListener(loginNotice);
        return messageConsumer;
    }
    @Bean("loginNotice")
    public MessageListener<MemberSignInEvent> loginNoticeListener(){
        return new MemberSignInNoticeListener();
    }
` 

How can this work be simplified??

**Comment by davidmarquis** [comment]
You should have a look at the example XML configuration provided in the README. This provides a good starting point to write your own Java-based configuration to setup the different classes that are part of the library and work together. 
There's a fair bit of components that need to be wired together for this library to work, but you do this once for your project so although I recognize this might be a little tedious, this should be very limited in impact to your overall time. 

Closing as I'm considering this a non-issue but please do not hesitate to contribute anything you'd see that could improve the overall experience in setting this up for projects in general.

Thanks!
